version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ibgambler/ib-gateway:"$CIRCLE_TAG" .
          docker push ibgambler/ib-gateway:"$CIRCLE_TAG"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
